[tool.pytest.ini_options]
pythonpath = [ "." ]
testpaths = [
    "tests"
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["E501", "D", "T201", "S101", "S311", "COM812", "ISC001", "ANN101", "ANN102"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"**/{tests,docs,tools}/*" = ["E402", "INP001"]
